import { useState, useEffect } from 'react'
import { BottomBar, Slide, useSlides } from '@lopezleandro03/canvas-engine'
import styles from './SpecDrivenSlide.module.css'

const rows = [
  {
    num: '01',
    from: { label: 'Code-Centric Delivery', text: 'Specs are minimal or informal — prompts used with AI agents are undocumented and forgotten.' },
    to:   { label: 'Spec-Centric Delivery',  text: 'Specs are the primary control surface; code is generated by AI. Reduces rework across teams.' },
  },
  {
    num: '02',
    from: { label: 'Human-Heavy Development', text: 'Engineers manually translate business needs directly into code.' },
    to:   { label: 'AI-Augmented Development', text: 'Agents handle the full lifecycle using domain-specific MCP tools.' },
  },
  {
    num: '03',
    from: { label: 'Docs as Afterthought', text: 'Written mainly for compliance or after-the-fact reference.' },
    to:   { label: 'Docs as Communication', text: 'Specs align stakeholders, preserve decisions, and provide context for maintenance.' },
  },
  {
    num: '04',
    from: { label: 'Value in Execution', text: 'Competitive advantage came from how fast you could build and deploy.' },
    to:   { label: 'Value in Design', text: 'Advantage comes from reusable Spec Templates that accelerate Proof of Value and scale.' },
  },
]

const STEPS = rows.length

export default function SpecDrivenSlide({ index }) {
  const { current } = useSlides()
  const [step, setStep] = useState(0)
  const isActive = current === index

  useEffect(() => { if (!isActive) setStep(0) }, [isActive])

  useEffect(() => {
    if (!isActive) return
    const handler = (e) => {
      if (e.key === 'ArrowRight' || e.key === ' ' || e.key === 'PageDown' || e.key === 'Enter') {
        if (step < STEPS) { e.preventDefault(); e.stopPropagation(); setStep(s => s + 1) }
      }
      if (e.key === 'ArrowLeft' || e.key === 'PageUp') {
        if (step > 0) { e.preventDefault(); e.stopPropagation(); setStep(s => s - 1) }
      }
    }
    document.addEventListener('keydown', handler, true)
    return () => document.removeEventListener('keydown', handler, true)
  }, [isActive, step])

  return (
    <Slide index={index} className={styles.slide}>
      <div className="accent-bar" />
      <div className={`orb ${styles.orb1}`} />
      <div className={`orb ${styles.orb2}`} />
      <div className={`orb ${styles.orb3}`} />

      <div className={styles.container}>
        <div className={styles.header}>
          <h2 className={styles.title}>
            What is <span className={styles.accent}>Spec-Driven Development</span>?
          </h2>
          <div className={styles.titleBar} />
          <p className={styles.subtitle}>A structured way to give agents the context they need to do the right thing</p>
        </div>

        <div className={styles.body}>
          {/* Column headers */}
          <div className={styles.colHeaders}>
            <div className={styles.colLabel} data-side="from">From</div>
            <div />
            <div className={styles.colLabel} data-side="to">To</div>
          </div>

          {rows.map((row, i) => (
            <div key={i} className={`${styles.row} ${step > i ? styles.visible : styles.hidden}`}>
              <div className={`${styles.card} ${styles.fromCard}`}>
                <span className={styles.num}>{row.num}</span>
                <div className={styles.cardContent}>
                  <span className={styles.fromLabel}>{row.from.label}</span>
                  <span className={styles.itemText}>{row.from.text}</span>
                </div>
              </div>

              <div className={styles.connector}>
                <div className={styles.connectorArrow}>→</div>
              </div>

              <div className={`${styles.card} ${styles.toCard}`}>
                <div className={styles.cardContent}>
                  <span className={styles.toLabel}>{row.to.label}</span>
                  <span className={styles.itemText}>{row.to.text}</span>
                </div>
                <span className={styles.glow} />
              </div>
            </div>
          ))}
        </div>
      </div>

      <BottomBar text="Nordcloud Developer Day 2026" />
    </Slide>
  )
}
